version: 0.0
os: linux
files:
   - source: /web
     destination: /var/www/html
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
   ApplicationStop:
    - location: lb_scripts/deregister_from_elb.sh
   BeforeInstall:
    - location: httpd_scripts/install_apache.sh
    - location: httpd_scripts/start_apache.sh
   AfterInstall:
    - location: httpd_scripts/restart_apache.sh
   ApplicationStart:
    - location: lb_scripts/register_with_elb.sh
